src/Entity/Membre.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembreRepository")
 */
class Membre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Cin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Statut")
     */
    private $Statut;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipe")
     */
    private $Equipe;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etablissement")
     */
    private $Etablissement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCin(): ?int
    {
        return $this->Cin;
    }

    public function setCin(int $Cin): self
    {
        $this->Cin = $Cin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->Statut;
    }

    public function setStatut(?Statut $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getEquipe(): ?Equipe
    {
        return $this->Equipe;
    }

    public function setEquipe(?Equipe $Equipe): self
    {
        $this->Equipe = $Equipe;

        return $this;
    }

    public function getEtablissement(): ?Etablissement
    {
        return $this->Etablissement;
    }

    public function setEtablissement(?Etablissement $Etablissement): self
    {
        $this->Etablissement = $Etablissement;

        return $this;
    }
}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Equipe;
use App\Entity\Etablissement;
use App\Entity\Membre;
use App\Entity\Statut;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Cin')
            ->add('Nom')
            ->add('Prenom')
            ->add('Email',EmailType::class)
            ->add('Adresse')
            ->add('Statut',EntityType::class,[
                'class'=>Statut::class,
                'choice_label'=>'Nom'
            ])
            ->add('Equipe',EntityType::class,[
                'class'=>Equipe::class,
                'choice_label'=>'Nom'
            ])
            ->add('Etablissement',EntityType::class,[
                'class'=>Etablissement::class,
                'choice_label'=>'Nom'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Form\MembreType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

    /**
     * @Route("/membre")
    */
class MembreController extends AbstractController
{
    //Ajouter un membre


    /**
     * @Route("/add", name="add_membre")
     */
    public function Add(Request $request)
    {
        $membre = new Membre();

        $form=$this->createForm(MembreType::class,$membre);

        $form->handleRequest($request);

        if ($form -> isSubmitted() && $form -> isValid()) {
            
             $em = $this -> getDoctrine()->getManager();
             $em->persist($membre);
             $em->flush();

             return $this->redirectToRoute("list_membre");
        }

        return $this->render('membre/formadd.html.twig', [
            'form' => $form->createView(),'btn'=>'Ajouter'
        ]);
    }

        //Modifier un membre 

      /**
     * @Route("/edit/{id}", name="edit_membre")
     */
    public function edit(Request $request, $id)
    {
        $membre = $this->getDoctrine()->getRepository(Membre::class)->find($id);

        $form=$this->createForm(MembreType::class,$membre);

        $form->handleRequest($request);

        if ($form -> isSubmitted() && $form -> isValid()) {
            
             $em = $this -> getDoctrine()->getManager();
             $em->persist($membre);
             $em->flush();

             return $this->redirectToRoute("list_membre");
        }

        return $this->render('membre/formadd.html.twig', [
            'form' => $form->createView(),'btn'=>'Modifier'
        ]);
    }

        //lister tous  les membres

     /**
     * @Route("/list", name="list_membre")
     */
    public function list()
    {
        $membre= $this->getDoctrine()->getRepository(Membre::class)->findAll();


        return $this->render('membre/list.html.twig', [
            'membres' => $membre,
        ]);
    }


    //supprimer un membre
    /**
     * @Route("/sup/{id}", name="sup_membre")
     */
    public function delete($id)
    {


        $membre= $this->getDoctrine()->getRepository(Membre::class)->find($id);

        if(!$membre) 
        {
            throw $this-> createNotFoundException(
                'Equipe id : '.$id.' est inexistant ..' 
            );
        }

        $em=$this->getDoctrine()->getManager();
        $em->remove($membre);
        $em->flush();

        return $this->redirectToRoute('list_membre');
    }


       //afficher detaile  d'un membre
       
    /**
     * @Route("/show/{id}", name="show_membre")
     */
    public function show($id)
    {

 
        $membre= $this->getDoctrine()->getRepository(Membre::class)->find($id);

        if(!$membre) 
        {
            throw $this-> createNotFoundException(
                'Equipe id : '.$id.' est inexistant ..' 
            );
        }

        return $this ->render('membre/show.html.twig',[
             'membre'=> $membre,
        ]);
    }

     /**
     * @Route("/membre", name="membre")
     */
    public function index()
    {
        return $this->render('membre/index.html.twig', [
            'controller_name' => 'MembreController',
        ]);
    }
}

templates/membre/formadd.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{ btn }} une Equipe </h1>
    
     {{ form_start(form) }}
     {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">{{ btn }}</button>
     {{ form_end(form) }}
     
</div>
{% endblock %}

templates/membre/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

    <h1 class="text-white bg-dark">La liste de tous les membres</h1>
    <table class="table table-striped">
        <tr>
            <td> ID</td>
            <td> Cin </td>
            <td> Nom </td>
            <td> Prenom </td>
            <td> Email </td>
            <td> Adresse </td>
            <td> Equipe </td>
            <td> Statut </td>
            <td> Etablissement </td>
        <tr> 
    {% for m in membres %}
       <tr>
           <td>{{ m.id}}</td>
           <td>{{ m.cin}}</td>
           <td>{{ m.nom}}</td>
           <td>{{ m.prenom}}</td>
           <td>{{ m.email}}</td>
           <td>{{ m.adresse}}</td>
           <td>{{ m.equipe.nom}}</td>
           <td>{{ m.statut.nom}}</td>
           <td>{{ m.etablissement.nom}}</td>
           <td><a href="{{path('show_membre',{'id':m.id})}}"><i class="fas fa-eye"></i></a></td>
           <td><a href="{{path('edit_membre',{'id':m.id})}}"><i class="fas fa-edit"></i></a></td>
             <td><a href="{{path('sup_membre',{'id':m.id})}}"><i class="fas fa-trash-alt"></i></a></td>
        </tr>
    {% else %}   

  <h2> la table membre est vide </h2>
    {% endfor %}
    </table>
    <p><a href="{{path('add_membre')}}">Ajouter un membre</a></p>

{% endblock %}

templates/membre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
     <h1> Equipe {{ membre.id}}</h1>
     <h3> Cin: </h3>
     <h5>{{ membre.cin}}</h5>
     <h3> Nom:</h3>{{ membre.nom}}
     <h3> Nom d'equipe:</h3>{{ membre.equipe.nom}}
     <h3> Nom statut:</h3>{{ membre.statut.nom}}

     <p><a href="{{path('list_membre')}}">retour</a></p>
</div>
{% endblock %}