src/Entity/Annonce.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnnonceRepository")
 */
class Annonce
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Contenu;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Form/AnnonceType.php
<?php

namespace App\Form;

use DateTime;
use App\Entity\Annonce;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class AnnonceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Titre')
            ->add('Contenu',TextareaType::class,['attr'=>['class'=>'tnymce']])
            ->add('Date',DateType::class)
        ;
    }

    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Annonce::class,
        ]);
    }
}

src/Controller/AnnonceController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Form\AnnonceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

    /**
     * @Route("/annonce")
     */

class AnnonceController extends AbstractController
{

    //Ajouter une annonce


    /**
     * @Route("/add", name="add_annonce")
     */

    public function Add(Request $request)
    {
        $annonce = new Annonce();

        $form=$this->createForm(AnnonceType::class,$annonce);

        $form->handleRequest($request);

        if ($form -> isSubmitted() && $form -> isValid()) {
            
             $em = $this -> getDoctrine()->getManager();
             $em->persist($annonce);
             $em->flush();

             return $this->redirectToRoute("list_annonce");
        }

        return $this->render('annonce/formadd.html.twig', [
            'form' => $form->createView(),'btn'=>'Ajouter'
        ]);
    }

    //Modifier une annonce 

      /**
     * @Route("/edit/{id}", name="edit_annonce")
     */
    public function edit(Request $request, $id)
    {
        $annonce = $this->getDoctrine()->getRepository(Annonce::class)->find($id);

        $form=$this->createForm(AnnonceType::class,$annonce);

        $form->handleRequest($request);

        if ($form -> isSubmitted() && $form -> isValid()) {
            
             $em = $this -> getDoctrine()->getManager();
             $em->persist($annonce);
             $em->flush();

             return $this->redirectToRoute("list_annonce");
        }

        return $this->render('annonce/formadd.html.twig', [
            'form' => $form->createView(),'btn'=>'Modifier'
        ]);
    }

    

        //lister tous les annonces

     /**
     * @Route("/list", name="list_annonce")
     */
    public function list()
    {
        $annonce= $this->getDoctrine()->getRepository(Annonce::class)->findAll();


        return $this->render('annonce/list.html.twig', [
            'annonces' => $annonce,
        ]);
    }

    //supprimer une annonce

    /**
     * @Route("/sup/{id}", name="sup_annonce")
     */
    public function delete($id)
    {


        $annonce= $this->getDoctrine()->getRepository(Annonce::class)->find($id);

        if(!$annonce) 
        {
            throw $this-> createNotFoundException(
                'Equipe id : '.$id.' est inexistant ..' 
            );
        }

        $em=$this->getDoctrine()->getManager();
        $em->remove($annonce);
        $em->flush();

        return $this->redirectToRoute('list_annonce');
    }

    //afficher detaile  d'une annonce
       
    /**
     * @Route("/show/{id}", name="show_annonce")
     */
    public function show($id)
    {

 
        $annonce= $this->getDoctrine()->getRepository(Annonce::class)->find($id);

        if(!$annonce) 
        {
            throw $this-> createNotFoundException(
                'Equipe id : '.$id.' est inexistant ..' 
            );
        }

        return $this ->render('annonce/show.html.twig',[
             'annonce'=> $annonce,
        ]);
    }




    /**
     * @Route("/annonce", name="annonce")
     */
    public function index()
    {
        return $this->render('annonce/index.html.twig', [
            'controller_name' => 'AnnonceController',
        ]);
    }
}

templates/annonce/formadd.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>{{ btn }} une Annonce </h1>
    
     {{ form_start(form) }}
     {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">{{ btn }}</button>
     {{ form_end(form) }}
</div>
{% endblock %}

templates/annonce/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AnnonceController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/conde224/TravauxSymfony/MiniProjet/src/Controller/AnnonceController.php'|file_link(0) }}">src/Controller/AnnonceController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/conde224/TravauxSymfony/MiniProjet/templates/annonce/index.html.twig'|file_link(0) }}">templates/annonce/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/annonce/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div>
    <h1 class="text-white bg-dark">la liste de toutes les annonces </h1>
    <table class="table table-responsive table-sm">
        <tr>
            <td> ID </td>
            <td> Titre</td>
            <td> Annonce </td>
             <td> Date d'ajout </td>
            
          
 
        </tr>  
    {% for a in annonces %}
       <tr>
           <td>{{ a.id }}</td> 
           <td>{{ a.titre }}</td>
           <td>{{ a.contenu }}</td>
           <td>{{ a.Date ? a.Date|date('Y-m-d') : '' }}</td>
           <td><a href="{{path('edit_annonce',{'id':a.id})}}"><i class="fas fa-edit"></i></a></td>
           <td><a href="{{path('show_annonce',{'id':a.id})}}"><i class="fas fa-eye"></i></a></td>
           <td><a href="{{path('sup_annonce',{'id':a.id})}}"><i class="fas fa-trash-alt"></i></a></td>
                    
        </tr>
    {% else %}   

  <h2> la table annonce est vide </h2>
    {% endfor %}
    </table>
    <p><a href="{{path('add_annonce')}}">Ajouter Annonce</a></p>
</div>
{% endblock %}

templates/annonce/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EquipeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
     <h1> Equipe {{ annonce.id}}</h1>
     <h1> Nom: {{ annonce.contenu}}</h1>
     

     <td><a href="{{path('list_annonce')}}">retour</a></td>
</div>
{% endblock %}